# Auto-generated from Formula/get-ssid.rb.tmpl by `make package`. Do not edit this file directly.
class GetSsid < Formula
  desc "Print current Wi-Fi SSID on macOS without Location permission"
  homepage "https://github.com/fjh658/get-ssid"
  license "MIT"
  version "1.0.2"

  tap_root = Pathname.new(__dir__).parent
  artifact = tap_root/"dist"/"get-ssid-1.0.2-macos-universal.tar.gz"
  url "file://#{artifact}"
  sha256 "fd209994a0ca5f37e25a9dbeb88f3efc009b48cf6a8111fc82eaad7f03270e31"

  depends_on :macos

  def install
    bin.install "get-ssid"
  end

  test do
    assert_match "USAGE:", shell_output("#{bin}/get-ssid --help")
  end
end
